In [0]:
from __future__ import print_function, absolute_import, division
import numpy as np
import tensorflow as tf

In [2]:
# set eager API
print("Setting eager API")
tf.enable_eager_execution()
tfe=tf.contrib.eager

Setting eager API


W0810 10:49:42.212704 140334703540096 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



In [3]:
# define constant tensors
print("Define constant tensors")
a=tf.constant(2)
print("a=%i"%a)
b=tf.constant(3)
print("b=%i"%b)


Define constant tensors
a=2
b=3


In [5]:
#run operations without tf.Session()
print("Running operations without tf.Session")
c=a+b
d=a*b
print("a+b:%i"%c)
print("a*b:%i"%d)

Running operations without tf.Session
a+b:5
a*b:6


In [7]:
# compatibility with Numpy
print("Mixing operations with TEnsors and Numpy")
a=tf.constant([[2.0,1.0],
              [1.0, 0.]],dtype=tf.float32)
print("tensor :\n a=%s"%a)
b=np.array([[3.0,0.],
           [5.,1.]],dtype=np.float32)
print("numpy array:\n b=%s"%b)

Mixing operations with TEnsors and Numpy
tensor :
 a=tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
numpy array:
 b=[[3. 0.]
 [5. 1.]]


In [9]:
print("running operations without tf.Session()")
c=a+b
d=tf.matmul(a,b)
print("a+b:%s"%c)
print("a*b:%s"%d)

running operations without tf.Session()
a+b:tf.Tensor(
[[5. 1.]
 [6. 1.]], shape=(2, 2), dtype=float32)
a*b:tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)


In [11]:
print("Iterate through tensor 'a'")
for i in range(a.shape[0]):
  for j in range(a.shape[1]):
    print(a[i][j])

Iterate through tensor 'a'
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
